### ISSUE TITLE
Which questionnaire platform we will use ?

### ISSUE THREAD

**Issue by alessandro-olivo** [fabcor-maxiv/mxcube-code-camp-2024-05-30#4]
Hi all,
should we start to create this questionnaire ? Have you some tool to propose, in case there are no other better solutions I can start creating a Google form.

**Comment by fabcor-maxiv** [comment]
I guess Google forms is a good candidate. Does it require a Google account?

**Comment by fabcor-maxiv** [comment]
What other options are there?

I know we have access to <https://forms.office.com/> via Lund University.

**Comment by alessandro-olivo** [comment]
> I guess Google forms is a good candidate. Does it require a Google account?

To create the Google Form you need an account, to fill it is not mandatory, just tested with this Mokup GForm https://forms.gle/T8vPpcmAXvztRv4N8 (let's try if you want)
Entering your email is necessary to receive an email containing a link that allows you to modify the answers already given

**Comment by alessandro-olivo** [comment]
We can go also with this https://forms.office.com/ (I've never tried it) since it's an "internal" service

**Comment by fabcor-maxiv** [comment]
I do not seem to manage to create a Google account with my work email address (maybe because it is a Microsoft account). And then the other way around, if we use the Office Forms from Microsoft I am not sure that you will be allowed to contribute (edit the questionnaire and see the answers). Maybe by Monday I will have figured out a way to obtain a Google account.

I know it is not ideal, but maybe for now, we should just stick to this `README.md` file in this repo as best as we can.

**Comment by fabcor-maxiv** [comment]
Ideally, I believe that reading all the answers should be as easy as filling in the form. Meaning that anyone should be allowed to see the answers after they filled the form. But I do not think this exists (not on Google, not on Microsoft Office).

**Comment by alessandro-olivo** [comment]
> I know it is not ideal, but maybe for now, we should just stick to this `README.md` file in this repo as best as we can.

I totally agree with you we, for now we can use this `README.md`, once we will be happy with the questions collected we can create the questionnaire

**Comment by alessandro-olivo** [comment]
> Ideally, I believe that reading all the answers should be as easy as filling in the form. Meaning that anyone should be allowed to see the answers after they filled the form. But I do not think this exists (not on Google, not on Microsoft Office).

If I'm not wrong, it should be possible to store the form answers in a Google sheet, maybe it possible to shared it in "only read" mode (to be checked)

**Comment by fabcor-maxiv** [comment]
I guess we will go for Google Forms.

> it should be possible to store the form answers in a Google sheet

Seems like it is possible and that is likely what we will do.
