### ISSUE TITLE
MXCuBE-Web only or MXCuBE-Qt as well?

### ISSUE THREAD

**Issue by fabcor-maxiv** [fabcor-maxiv/mxcube-code-camp-2024-05-30#6]
@alessandro-olivo @agruzinov @HilbertCorsair  @marcus-oscarsson

At MAXIV we only have MXCuBE-Web, so that is the only thing I know, and I always forget that there is also MXCuBE-Qt. For this questionnaire as well, I only had MXCuBE-Web in mind. So here comes the question...

Should this questionnaire target MXCuBE-Qt as well? If yes, does anyone have any experience with MXCuBE-Qt and could check that the questionnaire also makes sense for MXCuBE-Qt?

**Comment by alessandro-olivo** [comment]
This is a good point, here in Elettra we are only using the web so we have no mxcubeQT experience. 
In general, I think it's useful to share "howtos" and thus also for QT version develop/deploy etc., unless the short-medium term intention of all partners is to move to the web version (just a thought)

**Comment by agruzinov** [comment]
Thanks for mentioning it. I had a look already, and from my side, there are no specific Qt questions. The questionnaire is already covering it. The only thing I would add is the PyQt version because migrating between major versions is always a 50/50 chance that something blows up :)

**Comment by fabcor-maxiv** [comment]
> The only thing I would add is the PyQt version

Was added in <https://github.com/fabcor-maxiv/mxcube-code-camp-2024-05-30/pull/8>.
